title: Mobile Forensics
theme: minima
url: "https://sagravsd.github.io"  # The URL for your GitHub Pages site
baseurl: ""  # If your site is hosted on a subpath, set this to '/<your-repository-name>'. Otherwise, leave it blank for root.
